/**
 * Generates the icon files of the design system from Lucide (UI icons) and Simple Icons (brand
 * logos). Dev-time only — the outputs are committed and the site never runs Node:
 *
 *   cd design-system/icons && npm ci && npm run build
 *
 * Outputs (next to this file):
 *   icons.php     name => inner SVG markup, read by ac_icon() (design-system/php/ui.php)
 *   sprite.svg    one <symbol> per icon, for acIcon() in site scripts (<svg><use href="…#name">)
 *   fa-shim.css   renders the legacy Font Awesome classes (<i class="fa-solid fa-house">) with the
 *                 Lucide icon of the same meaning, for markup not migrated yet and for icons
 *                 stored in the database. Covers every Font Awesome name found in the repo.
 *
 * Names: Lucide names as is (house, trophy, triangle-alert…), brands as brand-<slug>
 * (brand-github, brand-discord…). fa-map.json maps Font Awesome names to those names.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const faMap = JSON.parse(readFileSync(join(here, 'fa-map.json'), 'utf8'));
delete faMap.$comment;

const BRANDS = ['github', 'discord', 'wikipedia', 'youtube', 'twitch', 'x', 'bluesky', 'reddit', 'facebook',
  'instagram', 'patreon', 'tiktok', 'mastodon'];

/** name => inner markup (stroke icons: paths as is; brands: wrapped in a filled group). */
const icons = {};

const lucideDir = join(here, 'node_modules', 'lucide-static', 'icons');
for (const file of readdirSync(lucideDir).filter((f) => f.endsWith('.svg')).sort()) {
  const svg = readFileSync(join(lucideDir, file), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  icons[file.slice(0, -4)] = minify(inner);
}
for (const slug of BRANDS) {
  const svg = readFileSync(join(here, 'node_modules', 'simple-icons', 'icons', `${slug}.svg`), 'utf8');
  const paths = svg.replace(/<title>[\s\S]*?<\/title>/, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  icons[`brand-${slug}`] = `<g fill="currentColor" stroke="none">${minify(paths)}</g>`;
}

for (const [fa, target] of Object.entries(faMap)) {
  if (!icons[target]) throw new Error(`fa-map.json: "${fa}" → "${target}", which is not an icon`);
}

// ---- icons.php ----
const php = ['<?php', '// Generated by design-system/icons/build.mjs — do not edit. Lucide (ISC) and Simple Icons (CC0).', 'return ['];
for (const [name, markup] of Object.entries(icons)) php.push(`    '${name}' => '${markup.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`);
php.push('];', '');
writeFileSync(join(here, 'icons.php'), php.join('\n'));

// ---- sprite.svg ----
const STROKE = 'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';
const sprite = ['<svg xmlns="http://www.w3.org/2000/svg">', '<!-- Generated by design-system/icons/build.mjs. Lucide (ISC) and Simple Icons (CC0). -->'];
for (const [name, markup] of Object.entries(icons)) sprite.push(`<symbol id="${name}" viewBox="0 0 24 24" ${STROKE}>${markup}</symbol>`);
sprite.push('</svg>', '');
writeFileSync(join(here, 'sprite.svg'), sprite.join('\n'));

// ---- fa-shim.css ----
const used = scanFontAwesomeNames();
const shimNames = [...new Set([...Object.keys(faMap), ...used])].sort();
const unknown = shimNames.filter((n) => !icons[faMap[n] ?? n]);
if (unknown.length) throw new Error(`Font Awesome names with no Lucide icon (add them to fa-map.json): ${unknown.join(', ')}`);

const css = [
  '/*',
  ' * Generated by design-system/icons/build.mjs — do not edit.',
  ' * Legacy Font Awesome markup (<i class="fa-solid fa-house">) drawn with the Lucide icon of the',
  ' * same meaning: the site no longer loads Font Awesome. New code uses ac_icon() / acIcon().',
  ' * The Altered glyphs (fa-kit / fak, assets/font/alteredicons.css) are not affected.',
  ' */',
  ':is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab) {',
  '  display: inline-block;',
  '  width: 1em;',
  '  height: 1em;',
  '  vertical-align: -0.125em;',
  '  background-color: currentColor;',
  '  -webkit-mask: var(--ac-fa-icon) center / contain no-repeat;',
  '  mask: var(--ac-fa-icon) center / contain no-repeat;',
  '  font-style: normal;',
  '  flex-shrink: 0;',
  '}',
  ':is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab)::before { content: none; }',
  ':is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab).fa-fw { width: 1.25em; }',
  ':is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab).fa-xs { font-size: 0.75em; }',
  ':is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab).fa-sm { font-size: 0.875em; }',
  ':is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab).fa-lg { font-size: 1.25em; vertical-align: -0.2em; }',
  ...[1, 2, 3, 4, 5].map((n) => `:is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab).fa-${n}x { font-size: ${n}em; }`),
  ':is(.fa-spin, .fa-pulse) { animation: ac-fa-spin 1s linear infinite; }',
  '@keyframes ac-fa-spin { to { transform: rotate(360deg); } }',
  '@media (prefers-reduced-motion: reduce) { :is(.fa-spin, .fa-pulse) { animation-duration: 3s; } }',
];
for (const name of shimNames) {
  const target = faMap[name] ?? name;
  const stroke = target.startsWith('brand-') ? '' : ` ${STROKE.replaceAll('currentColor', 'black')}`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"${stroke}>${icons[target].replaceAll('currentColor', 'black')}</svg>`;
  css.push(`.fa-${name}:is(.fa-solid, .fa-regular, .fa-brands, .fas, .far, .fab) { --ac-fa-icon: url("data:image/svg+xml,${encodeSvg(svg)}"); }`);
}
css.push('');
writeFileSync(join(here, 'fa-shim.css'), css.join('\n'));

console.log(`${Object.keys(icons).length} icons, ${shimNames.length} Font Awesome names in the shim`);

// ---------------------------------------------------------------------------------------------

function minify(markup) {
  return markup.replace(/<!--[\s\S]*?-->/g, '').replace(/\s*\n\s*/g, '').replace(/\s*\/>/g, '/>').trim();
}

function encodeSvg(svg) {
  return svg.replace(/"/g, "'").replace(/[#%<>{}]/g, (c) => encodeURIComponent(c));
}

/** Font Awesome icon names (without fa-) used anywhere in the repo's source. */
export function scanFontAwesomeNames() {
  const skip = /(^|\/)(node_modules|dist|\.angular|tinymce|uploads|vendor|\.git)(\/|$)/;
  const exts = /\.(php|js|json|sql|html|ts)$/;
  const modifiers = /^(solid|regular|brands|kit|spin|pulse|fw|xs|sm|lg|[0-9]+x|beat|fade|flip|shake|bounce|rotate-by|inverse|border|pull-left|pull-right|stack|stack-1x|stack-2x|ul|li)$/;
  const names = new Set();
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      const path = join(dir, entry);
      const rel = relative(repo, path);
      if (skip.test(rel) || rel.startsWith('design-system/icons')) continue;
      if (statSync(path).isDirectory()) walk(path);
      else if (exts.test(entry)) {
        const text = readFileSync(path, 'utf8');
        // A class list that carries a Font Awesome style prefix: fa-solid fa-house, fas fa-house…
        for (const m of text.matchAll(/\b(?:fa-solid|fa-regular|fa-brands|fas|far|fab)\b((?:\s+[\w-]+)+)|((?:[\w-]+\s+)+)(?:fa-solid|fa-regular)\b/g)) {
          for (const cls of (m[1] ?? m[2]).trim().split(/\s+/)) {
            if (!cls.startsWith('fa-')) continue;
            const name = cls.slice(3);
            if (!modifiers.test(name) && name !== '') names.add(name);
          }
        }
      }
    }
  };
  walk(repo);
  return [...names];
}
