<?php
// AlteredCore design system — PHP helpers for the shell and PHP plugins.
// Loaded by includes/functions.php, so every page and plugin can call them.
// PHP 7.4 compatible (production runs php:7.4-apache).

/** Absolute filesystem path of the design-system/ directory. */
function dsDir(): string {
    return dirname(__DIR__);
}

/** Public URL of a file under design-system/, with a cache-busting version. */
function dsUrl(string $rel): string {
    $file = dsDir() . '/' . $rel;
    $v    = is_file($file) ? '?v=' . filemtime($file) : '';
    return BASE_URL . '/design-system/' . $rel . $v;
}

/** Component stylesheets, in a stable order (css/components/*.css). */
function dsComponentFiles(): array {
    $files = glob(dsDir() . '/css/components/*.css') ?: [];
    sort($files);
    return array_map(function ($f) { return 'css/components/' . basename($f); }, $files);
}

/**
 * Stylesheets of the page's <head>, in cascade order. Bootstrap is loaded before them by the
 * shell; the bridges come last so they win over Bootstrap's own rules.
 */
function dsDocumentStylesheets(): array {
    return array_merge(
        ['fonts/fonts.css', 'tokens/tokens.css', 'css/base.css'],
        dsComponentFiles(),
        ['icons/fa-shim.css', 'css/bridges/bootstrap.css', 'css/bridges/legacy.css']
    );
}

/**
 * Stylesheets injected into every SPA plugin's shadow root (js/altered-core-host.js): the
 * base rules and the ac-* components. Tokens and fonts are not needed there — custom
 * properties inherit from <html> and @font-face only works in the document.
 */
function dsShadowStylesheets(): array {
    return array_merge(['css/base.css'], dsComponentFiles());
}

/**
 * Value of a colour token in tokens.css, for the places CSS cannot reach (theme-color meta, web app
 * manifest): 'light' reads `:root`, 'dark' reads `:root[data-theme='dark']` (then `:root`). A `var()`
 * value is resolved. null if missing.
 */
function dsToken(string $name, string $theme = 'light'): ?string {
    static $blocks = null;
    if ($blocks === null) {
        $css = (string)file_get_contents(dsDir() . '/tokens/tokens.css');
        $blocks = ['light' => '', 'dark' => ''];
        if (preg_match('/^:root \{(.*?)^\}/ms', $css, $m)) $blocks['light'] = $m[1];
        if (preg_match("/^:root\[data-theme='dark'\] \{(.*?)^\}/ms", $css, $m)) $blocks['dark'] = $m[1];
    }
    // The dark block only lists what changes: a token missing there takes its light value.
    $value = null;
    foreach ($theme === 'dark' ? ['dark', 'light'] : ['light'] as $t) {
        if (preg_match('/' . preg_quote($name, '/') . ':\s*([^;]+);/', $blocks[$t] ?? '', $m)) { $value = trim($m[1]); break; }
    }
    // A token that points at another one (var(--ac-…)) is resolved in the same theme.
    if ($value !== null && preg_match('/^var\((--[\w-]+)\)$/', $value, $m)) return dsToken($m[1], $theme);
    return $value;
}

/** Inline script for <head>: sets data-density before the first paint (see tokens.css). */
function dsDensityScript(): string {
    return "(function(){var r=document.documentElement,c=matchMedia('(pointer: coarse)'),w=matchMedia('(max-width: 767.98px)');"
         . "function s(){r.setAttribute('data-density',c.matches||w.matches?'touch':'pointer');}"
         . "s();c.addEventListener('change',s);w.addEventListener('change',s);}());";
}

/** name => inner SVG markup (generated by design-system/icons/build.mjs). */
function dsIcons(): array {
    static $icons = null;
    if ($icons === null) $icons = require dsDir() . '/icons/icons.php';
    return $icons;
}

/** Font Awesome name => icon name (design-system/icons/fa-map.json). */
function dsFaMap(): array {
    static $map = null;
    if ($map === null) {
        $map = json_decode((string)file_get_contents(dsDir() . '/icons/fa-map.json'), true) ?: [];
        unset($map['$comment']);
    }
    return $map;
}

/**
 * Resolves an icon reference to an icon name, or null when unknown. Accepts a Lucide name
 * ("house"), a brand ("brand-github") or a legacy Font Awesome class list
 * ("fa-solid fa-house me-1", as stored in the menus); other classes of the list are returned
 * in $extraClasses.
 */
function dsResolveIcon(string $ref, ?array &$extraClasses = null): ?string {
    $extraClasses = [];
    $icons = dsIcons();
    $ref   = trim($ref);
    if ($ref === '') return null;
    if (strpos($ref, ' ') === false && strpos($ref, 'fa-') !== 0) {
        return isset($icons[$ref]) ? $ref : null;
    }
    $name = null;
    foreach (preg_split('/\s+/', $ref) as $cls) {
        if (in_array($cls, ['fa-solid', 'fa-regular', 'fa-brands', 'fas', 'far', 'fab', 'fa', 'fa-fw'], true)) continue;
        if (strpos($cls, 'fa-') === 0 && $name === null) {
            $fa   = substr($cls, 3);
            $map  = dsFaMap();
            $cand = $map[$fa] ?? $fa;
            if (isset($icons[$cand])) { $name = $cand; continue; }
        }
        if (in_array($cls, ['fa-spin', 'fa-pulse'], true)) { $extraClasses[] = 'ac-icon--spin'; continue; }
        if (strpos($cls, 'fa-') === 0) continue;
        $extraClasses[] = $cls;
    }
    return $name;
}

/**
 * Inline SVG icon (Lucide, stroke 2; brand logos filled). Decorative by default
 * (aria-hidden); pass $label for an icon that carries meaning on its own.
 *
 *   <?= ac_icon('house') ?>
 *   <?= ac_icon('trash-2', 'ac-icon--16') ?>
 *   <?= ac_icon($navItem['icon']) ?>          // also accepts "fa-solid fa-house" (menus in DB)
 *
 * The Altered glyph font (fak fa-collection…) is not an SVG icon: those references are
 * rendered as <i class="…"> unchanged. Unknown names render nothing.
 */
function ac_icon(string $ref, string $class = '', ?string $label = null): string {
    if (preg_match('/(^|\s)(fak|fa-kit)(\s|$)/', $ref)) {
        return '<i class="' . htmlspecialchars(trim($ref . ' ' . $class), ENT_QUOTES, 'UTF-8') . '" aria-hidden="true"></i>';
    }
    $extra = [];
    $name  = dsResolveIcon($ref, $extra);
    if ($name === null) return '';
    $classes = trim('ac-icon ' . implode(' ', $extra) . ' ' . $class);
    $a11y    = $label !== null && $label !== ''
        ? ' role="img" aria-label="' . htmlspecialchars($label, ENT_QUOTES, 'UTF-8') . '"'
        : ' aria-hidden="true" focusable="false"';
    return '<svg class="' . htmlspecialchars($classes, ENT_QUOTES, 'UTF-8') . '" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
         . ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round"' . $a11y . '>' . dsIcons()[$name] . '</svg>';
}
